-- Guest checkout + secure claim: lets a visitor pay WITHOUT an account, then attach the paid
-- order to an account afterwards ("claim") using a single-use secret token.
--
-- Additive / relaxing only. Does not touch products, user_entitlements, order_items, any price,
-- any RLS policy, or the custom-plan tables/RPCs. Existing rows are unaffected (every existing
-- order keeps its user_id; the new columns are NULL for them).
--
-- Deploy order: apply this migration BEFORE the code that uses it. The currently deployed code
-- keeps working against it (it calls create_pending_order with two named args, which still
-- resolves to the new function via the defaulted trailing parameters).
--
-- Security model:
--   * The claim token is 32 random bytes generated by the server. ONLY its SHA-256 hash is stored
--     here (claim_token_hash); the plaintext exists only in the buyer's redirect URL.
--   * An unclaimed guest order (user_id IS NULL) is invisible to every client: the existing RLS
--     policies compare user_id = auth.uid(), which is never true for NULL. Only service_role
--     server code can read or claim it.
--   * claim_guest_order() is the ONLY way an order gets an owner after creation. It is service_role
--     only, runs as ONE statement-level transaction, requires status = 'paid', and flips user_id
--     in a single conditional UPDATE, so two concurrent/repeated claims can never both win.
--   * guest_email is stored for the payment receipt / support only. It is never used to authorize
--     anything.

-- ── orders: allow guest orders and track the claim ───────────────────────────────────────────
alter table public.orders
  alter column user_id drop not null;

alter table public.orders
  add column if not exists guest_email text,
  add column if not exists claim_token_hash text,
  add column if not exists claim_expires_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists claimed_at timestamptz;

-- One token hash identifies exactly one order. NULLs (all logged-in orders) are allowed many times.
create unique index if not exists orders_claim_token_hash_key
  on public.orders (claim_token_hash)
  where claim_token_hash is not null;

-- An order can never be ownerless AND unclaimable, and "claimed" always implies an owner.
alter table public.orders
  drop constraint if exists orders_owner_or_claim_chk;
alter table public.orders
  add constraint orders_owner_or_claim_chk check (user_id is not null or claim_token_hash is not null);

alter table public.orders
  drop constraint if exists orders_claim_state_chk;
alter table public.orders
  add constraint orders_claim_state_chk check (claimed_at is null or user_id is not null);

-- Defense in depth: once an order has an owner, that owner can never be changed or removed by an
-- UPDATE, whatever code (or future bug) tries it. This is what guarantees "never claimable by more
-- than one user" at the database level, independent of the application.
create or replace function public.orders_user_id_is_immutable()
returns trigger
language plpgsql
as $$
begin
  if old.user_id is not null and new.user_id is distinct from old.user_id then
    raise exception 'orders.user_id cannot be changed once an order has an owner';
  end if;
  return new;
end;
$$;

drop trigger if exists orders_user_id_immutable on public.orders;
create trigger orders_user_id_immutable
before update on public.orders
for each row
execute function public.orders_user_id_is_immutable();

-- ── create_pending_order: now also creates GUEST orders ──────────────────────────────────────
-- Same trust model as before (service_role only; the caller resolves identity first):
--   * logged-in order : p_user_id = verified user id, p_claim_token_hash = NULL
--   * guest order     : p_user_id = NULL, p_claim_token_hash = sha256 hex of the server-made token
-- Prices still come ONLY from public.products here -- never from the caller.
drop function if exists public.create_pending_order(uuid, text[]);

create or replace function public.create_pending_order(
  p_user_id uuid,
  p_product_slugs text[],
  p_claim_token_hash text default null,
  p_guest_email text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slugs text[];
  v_slug_count int;
  v_active_count int;
  v_total numeric;
  v_order public.orders;
  v_email text;
begin
  if p_user_id is null then
    -- Guest order: a well-formed token hash is mandatory (otherwise nobody could ever claim it).
    if p_claim_token_hash is null or p_claim_token_hash !~ '^[0-9a-f]{64}$' then
      raise exception 'create_pending_order: a guest order requires a valid claim token hash';
    end if;
    v_email := nullif(left(trim(coalesce(p_guest_email, '')), 254), '');
  else
    -- Logged-in order: never carries a claim token or guest email.
    if p_claim_token_hash is not null then
      raise exception 'create_pending_order: a logged-in order must not have a claim token';
    end if;
    v_email := null;
  end if;

  select array_agg(distinct s) into v_slugs
  from unnest(coalesce(p_product_slugs, array[]::text[])) as s
  where s is not null and length(trim(s)) > 0;

  v_slug_count := coalesce(array_length(v_slugs, 1), 0);
  if v_slug_count = 0 then
    raise exception 'create_pending_order: at least one product slug is required';
  end if;

  select count(*) into v_active_count
  from public.products
  where slug = any(v_slugs) and active = true;

  if v_active_count <> v_slug_count then
    raise exception 'create_pending_order: one or more requested products are invalid or inactive';
  end if;

  select coalesce(sum(price_ils), 0) into v_total
  from public.products
  where slug = any(v_slugs) and active = true;

  insert into public.orders (user_id, status, total_ils, currency, claim_token_hash, guest_email)
  values (p_user_id, 'pending', v_total, 'ILS', p_claim_token_hash, v_email)
  returning * into v_order;

  insert into public.order_items (order_id, product_id, price_ils_at_purchase)
  select v_order.id, p.id, p.price_ils
  from public.products p
  where p.slug = any(v_slugs) and p.active = true;

  return v_order;
end;
$$;

revoke all on function public.create_pending_order(uuid, text[], text, text) from public;
revoke all on function public.create_pending_order(uuid, text[], text, text) from anon;
revoke all on function public.create_pending_order(uuid, text[], text, text) from authenticated;
grant execute on function public.create_pending_order(uuid, text[], text, text) to service_role;

-- ── claim_guest_order: atomically attach a PAID guest order to an authenticated user ──────────
-- p_user_id MUST be the verified auth user (resolved by the server via auth.getUser()); this
-- function is unreachable from the browser (service_role only), exactly like create_pending_order.
-- Returns one of: 'claimed' | 'already_yours' | 'not_paid_yet' | 'invalid'.
-- 'invalid' deliberately covers unknown, expired, already-claimed-by-someone-else and unpaid-and-dead
-- orders alike, so a caller learns nothing about other people's orders.
create or replace function public.claim_guest_order(p_token_hash text, p_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_row public.orders;
begin
  if p_user_id is null then
    raise exception 'claim_guest_order: p_user_id is required';
  end if;

  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    return 'invalid';
  end if;

  -- THE atomic step. One conditional UPDATE: the row lock makes a concurrent/second claim wait,
  -- then re-evaluate "user_id is null" against the committed result (now false) and update 0 rows.
  update public.orders
  set user_id = p_user_id,
      claimed_at = now()
  where claim_token_hash = p_token_hash
    and user_id is null
    and status = 'paid'
    and (claim_expires_at is null or claim_expires_at > now())
  returning id into v_order_id;

  if v_order_id is not null then
    -- Same transaction as the ownership change: if this insert fails, the UPDATE above rolls back.
    insert into public.user_entitlements (user_id, product_id, source, payment_reference)
    select p_user_id, oi.product_id, 'allpay', v_order_id::text
    from public.order_items oi
    where oi.order_id = v_order_id
    on conflict (user_id, product_id) do nothing;

    return 'claimed';
  end if;

  select * into v_row from public.orders where claim_token_hash = p_token_hash;
  if not found then
    return 'invalid';
  end if;

  if v_row.user_id = p_user_id then
    return 'already_yours';
  end if;

  if v_row.user_id is null and v_row.status = 'pending' then
    return 'not_paid_yet';
  end if;

  return 'invalid';
end;
$$;

revoke all on function public.claim_guest_order(text, uuid) from public;
revoke all on function public.claim_guest_order(text, uuid) from anon;
revoke all on function public.claim_guest_order(text, uuid) from authenticated;
grant execute on function public.claim_guest_order(text, uuid) to service_role;

-- ── claim_guest_order_status: read-only status for the claim page (no ownership change) ──────
-- Lets the claim page decide what to show ("confirming payment" vs "payment successful, sign in" vs
-- "ready to add to your account") without changing anything. Returns only a coarse state, never any
-- order data: 'pending' | 'paid' | 'mine' | 'invalid'. 'mine' is returned only when the optional
-- p_viewer_id (the server-verified signed-in user) already owns the order, so re-opening your own
-- claimed link is friendly while a stranger learns nothing.
create or replace function public.claim_guest_order_status(p_token_hash text, p_viewer_id uuid default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.orders;
begin
  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    return 'invalid';
  end if;

  select * into v_row from public.orders where claim_token_hash = p_token_hash;
  if not found then
    return 'invalid';
  end if;

  if v_row.user_id is not null then
    if p_viewer_id is not null and v_row.user_id = p_viewer_id then
      return 'mine';
    end if;
    return 'invalid';
  end if;

  if v_row.status = 'pending' then
    return 'pending';
  end if;

  if v_row.status = 'paid' and (v_row.claim_expires_at is null or v_row.claim_expires_at > now()) then
    return 'paid';
  end if;

  return 'invalid';
end;
$$;

revoke all on function public.claim_guest_order_status(text, uuid) from public;
revoke all on function public.claim_guest_order_status(text, uuid) from anon;
revoke all on function public.claim_guest_order_status(text, uuid) from authenticated;
grant execute on function public.claim_guest_order_status(text, uuid) to service_role;

-- ── Support: re-issue a lost claim link (run manually in the SQL editor, never from the app) ──
-- 1. Find the paid, unclaimed order:
--      select id, guest_email, paid_at, claim_expires_at from public.orders
--      where user_id is null and status = 'paid' order by paid_at desc;
-- 2. Generate a new token OUTSIDE the database (e.g. `node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"`),
--    hash it (`node -e "console.log(require('crypto').createHash('sha256').update(process.argv[1]).digest('hex'))" <token>`),
--    then:
--      update public.orders set claim_token_hash = '<sha256 hex>', claim_expires_at = now() + interval '30 days'
--      where id = '<order id>' and user_id is null and status = 'paid';
--    and send the customer  https://travel-smarter-gamma.vercel.app/claim-purchase?token=<token>
